from .callback_datas import almau_shop_faq_callback, almau_shop_faq_edit_callback, almau_shop_faq_delete_callback, \
    main_faq_edit_callback, main_faq_delete_callback, main_faq_callback
from .schedule_buttons import inline_keyboard_schedule
from .menu_buttons import inline_keyboard_menu
from .admin_buttons import inline_keyboard_admin, inline_keyboard_massive_send_all, inline_keyboard_cancel_or_send, \
    inline_keyboard_cancel, cancel_or_send_schedule, inline_keyboard_update_schedule, cancel_or_update_schedule, \
    inline_keyboard_delete_schedule, cancel_or_delete_schedule, inline_keyboard_almau_shop_admin, \
    inline_keyboard_schedule_admin, inline_keyboard_add_almaushop_faq_or_cancel, almau_shop_faq_delete_callback, \
    cancel_or_delete_faq_almau_shop, inline_keyboard_edit_faq_almaushop_choice, \
    inline_keyboard_edit_almaushop_faq_or_cancel, inline_keyboard_edit_button_content_almaushop_or_cancel, \
    inline_keyboard_faq_admin, inline_keyboard_add_main_faq_or_cancel, inline_keyboard_edit_main_faq, \
    inline_keyboard_edit_main_faq_choice, inline_keyboard_edit_almaushop_faq_or_cancel, inline_keyboard_nav_university_admin_menu, \
    inline_keyboard_contact_center_admin, cancel_or_send_contact_center_admin, inline_keyboard_contacts_center_update, \
    cancel_or_update_contact_center_admin, inline_keyboard_contacts_center_delete, cancel_or_delete_contact_center_admin, \
    inline_keyboard_certificate_admin, cancel_or_send_certificate, cancel_or_update_certificate, cancel_or_delete_certificate, \
    inline_keyboard_update_certificate, inline_keyboard_delete_certificate, inline_keyboard_get_request_certificate
from .feedback_buttons import inline_keyboard_feedback, inline_keyboard_send_msg_data
from .almaushop_buttons import inline_keyboard_faq_almaushop, inline_keyboard_faq_almaushop_back
from .navigation_buttons import inline_keyboard_nav_unifi, inline_keyboard_contacts_center, \
    inline_keyboard_contacts_center_back
from .certificate_buttons import inline_keyboard_certificate, inline_keyboard_get_certificate, inline_keyboard_send_req_data
