from .menu_def_buttons import keyboard_send_phone_to_register_in_db, always_stay_menu_keyboard
from .def_library_buttons import keyboard_library, keyboard_library_choice_db, keyboard_library_send_phone
from .def_almaushop_buttons import keyboard_almaushop
from .def_feedback_buttons import keyboard_feedback, keyboard_feedback_send_phone
from .def_request_buttons import keyboard_request_send_phone, keyboard_certificate_type
